
name: "code checks"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install ruff
        pip install mypy
    - name: ruff stuff
      run: |
        ruff check
        ruff format
    - name: mypy
      run: |
        mypy src/